@startuml "Class Diagram"

skin rose

skinparam class {
    BackgroundColor<<Model>> #FFB2B2
}

skinparam class {
    BackgroundColor<<Controller>> #FFFBD7
}

skinparam class {
    BackgroundColor<<View>> #D9FFB2
}


class Flight <<Model>> {
    + id: Integer
    + departure_airport: Airport
    + arrival_airport: Airport
    + departure_time: DateTime
    + arrival_time: DateTime
    + aircraft: Aircraft
    ~ __str__()
}

class Aircraft<<Model>> {
    + model: String
    + capacity: Integer
    + code: String
    ~ __str__()
}

class Airport<<Model>> {
    + code: String
    + city: String
    + name: String
    + latitude: Float
    + longitude: Float
    ~ __str__()
}

class Passenger<<Model>> {
    + name: String
    + date_of_birth: Date
    + sex: Sex
    + email: Email
    + phone: String
    + citizen_identify_id: String
    + relation: Passenger
    ~ __str__()
}

class Booking<<Model>> {
    + flight: Flight
    + passengers: Passenger[]
    + booking_date: DateTime
    + total_fare: Decimal
    ~ __str__()
}

class BookingView<<View>> {
    permission_classes: list[IsAuthenticated]

    + get(request: HttpRequest) -> JsonResponse
}


class FlightAdmin<<View>> {
    - form: FlightForm
    - list_display: str[]
    - search_fields: str[]
    - ate_hierarchy: str
    - list_filter: str[]
    - list_per_page: int
    - total_passenger()
    - avaiable_seat()
    - capacity()
    - aircraft_code()
    - duration_time()
    - has_change_permission()
    - has_delete_permission()
}

class AircraftAdmin<<View>> {
    - list_display: str[]
    - search_fields: str[]
    - list_filter: str[]
    - list_per_page: int
}

class AirportAdmin<<View>> {
    - list_display: str[]
    - search_fields: str[]
    - list_filter: str[]
    - list_per_page: int
}

class PassengerAdmin<<View>> {
    - list_display: str[]
    - search_fields: str[]
    - list_per_page: int
}

class BookingAdmin<<View>> {
    - form: BookingForm
    - filter_horizontal: str[]
    - search_fields: str[]
    - list_display: str[]
    - list_filter: str[]
    - get_queryset()
    - has_change_permission()
    - has_delete_permission()
}



FlightAdmin --> Flight
AircraftAdmin --> Aircraft
AirportAdmin --> Airport
PassengerAdmin --> Passenger
BookingAdmin --> Booking
BookingView --> Booking

Passenger ..o Passenger: relation
Flight --o Airport: departure_airport
Flight --o Airport: arrival_airport
Flight --o Aircraft
Booking --o Flight
Booking --o Passenger


@enduml
