# Generated by Django 5.0.4 on 2024-05-07 14:22

import aviation.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aircraft",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "model",
                    models.CharField(
                        max_length=100,
                        validators=[
                            django.core.validators.MinLengthValidator(4),
                            django.core.validators.MaxLengthValidator(100),
                        ],
                    ),
                ),
                (
                    "capacity",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(100),
                            django.core.validators.MaxValueValidator(1000),
                        ]
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=8,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            django.core.validators.MaxLengthValidator(8),
                        ],
                    ),
                ),
            ],
            options={
                "db_table": "aviation_aircraft",
            },
        ),
        migrations.CreateModel(
            name="Airport",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "code",
                    models.CharField(
                        max_length=10,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            django.core.validators.MaxLengthValidator(10),
                        ],
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(4),
                            django.core.validators.MaxLengthValidator(100),
                        ],
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200,
                        validators=[
                            django.core.validators.MinLengthValidator(4),
                            django.core.validators.MaxLengthValidator(200),
                        ],
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
            ],
            options={
                "db_table": "aviation_airport",
            },
        ),
        migrations.CreateModel(
            name="Flight",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("departure_time", models.DateTimeField()),
                ("arrival_time", models.DateTimeField()),
                ("aircraft", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="aviation.aircraft")),
                (
                    "arrival_airport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="arrivals", to="aviation.airport"
                    ),
                ),
                (
                    "departure_airport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="departures", to="aviation.airport"
                    ),
                ),
            ],
            options={
                "db_table": "aviation_flight",
            },
        ),
        migrations.CreateModel(
            name="Passenger",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        validators=[
                            django.core.validators.MinLengthValidator(6),
                            django.core.validators.MaxLengthValidator(100),
                        ],
                    ),
                ),
                ("date_of_birth", models.DateField(validators=[aviation.models.validate_date_of_birth])),
                ("sex", models.CharField(choices=[("M", "Nam"), ("F", "Nữ"), ("O", "Khác")], max_length=1)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, validators=[django.core.validators.EmailValidator()]
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, validators=[django.core.validators.MaxLengthValidator(20)]
                    ),
                ),
                (
                    "citizen_identify_id",
                    models.CharField(
                        blank=True, max_length=15, null=True, validators=[django.core.validators.MaxLengthValidator(15)]
                    ),
                ),
                (
                    "relation",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="aviation.passenger"
                    ),
                ),
            ],
            options={
                "db_table": "aviation_passenger",
            },
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("booking_date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "total_fare",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("flight", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="aviation.flight")),
                ("passengers", models.ManyToManyField(to="aviation.passenger")),
            ],
            options={
                "db_table": "aviation_booking",
            },
        ),
    ]
