# Generated by Django 5.0.3 on 2024-03-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aviation", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="passenger",
        ),
        migrations.AddField(
            model_name="booking",
            name="passengers",
            field=models.ManyToManyField(to="aviation.passenger"),
        ),
    ]
