# Generated by Django 5.0.3 on 2024-03-27 07:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aviation", "0002_remove_booking_passenger_booking_passengers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="booking_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
